'use client'

import { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Box,
  Play,
  Square,
  RotateCcw,
  FolderTree,
  FileCode,
  File,
  Folder,
  ChevronRight,
  ChevronDown,
  Terminal,
  Eye,
  Clock,
  CheckCircle,
  XCircle,
  Loader2,
  Plus,
  Trash2,
  Download,
  Copy,
  RefreshCcw,
  Search,
  Code,
  Save,
  X,
  Zap,
  FolderOpen,
  FileText,
  Image,
  AlertTriangle,
  Cpu,
  HardDrive,
  Clock as ClockIcon,
} from 'lucide-react'
import { useAgentOSStore } from '@/lib/store'

// ─── Types ─────────────────────────────────────────────────────────

interface SandboxFile {
  name: string
  path: string
  type: 'file' | 'directory'
  size: number
  modified: string
  content?: string
  children?: SandboxFile[]
}

interface SandboxProcess {
  id: string
  agentId: string
  agentName: string
  agentAvatar: string
  command: string
  status: 'running' | 'completed' | 'failed' | 'queued'
  output: string
  exitCode: number | null
  startedAt: string
  completedAt: string | null
  duration: number | null
  filesCreated: string[]
  filesModified: string[]
}

interface SandboxSession {
  id: string
  name: string
  workingDir: string
  createdAt: string
  processes: SandboxProcess[]
  fileTree: SandboxFile[]
}

// ─── Sandbox Demo Data ─────────────────────────────────────────────

const DEMO_FILE_TREE: SandboxFile[] = [
  {
    name: 'my-project',
    path: '/sandbox/my-project',
    type: 'directory',
    size: 0,
    modified: new Date().toISOString(),
    children: [
      {
        name: 'src',
        path: '/sandbox/my-project/src',
        type: 'directory',
        size: 0,
        modified: new Date().toISOString(),
        children: [
          {
            name: 'index.ts',
            path: '/sandbox/my-project/src/index.ts',
            type: 'file',
            size: 1247,
            modified: new Date().toISOString(),
            content: `import express from 'express';
import { config } from './config';
import { router } from './routes';
import { logger } from './utils/logger';

const app = express();

app.use(express.json());
app.use('/api', router);

app.listen(config.port, () => {
  logger.info(\`Server running on port \${config.port}\`);
});

export default app;`,
          },
          {
            name: 'config.ts',
            path: '/sandbox/my-project/src/config.ts',
            type: 'file',
            size: 423,
            modified: new Date().toISOString(),
            content: `export const config = {
  port: process.env.PORT || 3000,
  db: {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432'),
    name: process.env.DB_NAME || 'agentos',
  },
  jwt: {
    secret: process.env.JWT_SECRET || 'change-me-in-production',
    expiresIn: '24h',
  },
};`,
          },
          {
            name: 'routes.ts',
            path: '/sandbox/my-project/src/routes.ts',
            type: 'file',
            size: 892,
            modified: new Date().toISOString(),
            content: `import { Router } from 'express';
import { agentRouter } from './routes/agents';
import { workflowRouter } from './routes/workflows';
import { healthCheck } from './middleware/health';

export const router = Router();

router.get('/health', healthCheck);
router.use('/agents', agentRouter);
router.use('/workflows', workflowRouter);

// 404 handler
router.use((_req, res) => {
  res.status(404).json({ error: 'Not found' });
});`,
          },
          {
            name: 'utils',
            path: '/sandbox/my-project/src/utils',
            type: 'directory',
            size: 0,
            modified: new Date().toISOString(),
            children: [
              {
                name: 'logger.ts',
                path: '/sandbox/my-project/src/utils/logger.ts',
                type: 'file',
                size: 312,
                modified: new Date().toISOString(),
                content: `import winston from 'winston';

export const logger = winston.createLogger({
  level: 'info',
  format: winston.format.json(),
  transports: [
    new winston.transports.Console(),
    new winston.transports.File({ filename: 'error.log', level: 'error' }),
  ],
});`,
              },
            ],
          },
        ],
      },
      {
        name: 'package.json',
        path: '/sandbox/my-project/package.json',
        type: 'file',
        size: 678,
        modified: new Date().toISOString(),
        content: `{
  "name": "my-project",
  "version": "1.0.0",
  "description": "Generated by AgentOS Sandbox",
  "main": "dist/index.js",
  "scripts": {
    "dev": "ts-node-dev src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js",
    "test": "jest"
  },
  "dependencies": {
    "express": "^4.18.2",
    "winston": "^3.11.0"
  },
  "devDependencies": {
    "typescript": "^5.3.3",
    "ts-node-dev": "^2.0.0",
    "@types/express": "^4.17.21"
  }
}`,
      },
      {
        name: 'tsconfig.json',
        path: '/sandbox/my-project/tsconfig.json',
        type: 'file',
        size: 456,
        modified: new Date().toISOString(),
        content: `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "lib": ["ES2022"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}`,
      },
      {
        name: 'Dockerfile',
        path: '/sandbox/my-project/Dockerfile',
        type: 'file',
        size: 289,
        modified: new Date().toISOString(),
        content: `FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --production
COPY dist ./dist
EXPOSE 3000
CMD ["node", "dist/index.js"]`,
      },
      {
        name: '.env.example',
        path: '/sandbox/my-project/.env.example',
        type: 'file',
        size: 156,
        modified: new Date().toISOString(),
        content: `PORT=3000
DB_HOST=localhost
DB_PORT=5432
DB_NAME=agentos
JWT_SECRET=change-me-in-production`,
      },
    ],
  },
]

const DEMO_PROCESSES: SandboxProcess[] = [
  {
    id: 'proc-1',
    agentId: 'agent-code',
    agentName: 'Code Reviewer',
    agentAvatar: '🔎',
    command: 'npx tsc --noEmit',
    status: 'completed',
    output: `src/index.ts(1,8): error TS2307: Cannot find module 'express'.
src/routes.ts(1,25): error TS2307: Cannot find module 'express'.

Found 2 errors. Watch mode: false.

Note: Run 'npm install' to install missing dependencies before type-checking.`,
    exitCode: 1,
    startedAt: new Date(Date.now() - 120000).toISOString(),
    completedAt: new Date(Date.now() - 118000).toISOString(),
    duration: 2000,
    filesCreated: [],
    filesModified: [],
  },
  {
    id: 'proc-2',
    agentId: 'agent-code',
    agentName: 'Code Reviewer',
    agentAvatar: '🔎',
    command: 'npm install',
    status: 'completed',
    output: `added 68 packages in 3.2s

8 packages are looking for funding
  run \`npm fund\` for details`,
    exitCode: 0,
    startedAt: new Date(Date.now() - 115000).toISOString(),
    completedAt: new Date(Date.now() - 112000).toISOString(),
    duration: 3000,
    filesCreated: ['package-lock.json', 'node_modules/'],
    filesModified: ['package.json'],
  },
  {
    id: 'proc-3',
    agentId: 'agent-devops',
    agentName: 'DevOps Automator',
    agentAvatar: '🚀',
    command: 'npx tsc --noEmit',
    status: 'completed',
    output: `No errors found. Type checking completed successfully.`,
    exitCode: 0,
    startedAt: new Date(Date.now() - 110000).toISOString(),
    completedAt: new Date(Date.now() - 108000).toISOString(),
    duration: 2000,
    filesCreated: [],
    filesModified: [],
  },
  {
    id: 'proc-4',
    agentId: 'agent-devops',
    agentName: 'DevOps Automator',
    agentAvatar: '🚀',
    command: 'npm run build',
    status: 'completed',
    output: `> my-project@1.0.0 build
> tsc

Compilation complete. Output written to ./dist/
  - dist/index.js
  - dist/config.js
  - dist/routes.js
  - dist/utils/logger.js`,
    exitCode: 0,
    startedAt: new Date(Date.now() - 105000).toISOString(),
    completedAt: new Date(Date.now() - 100000).toISOString(),
    duration: 5000,
    filesCreated: ['dist/index.js', 'dist/config.js', 'dist/routes.js', 'dist/utils/logger.js'],
    filesModified: [],
  },
  {
    id: 'proc-5',
    agentId: 'agent-test',
    agentName: 'Test Engineer',
    agentAvatar: '🧪',
    command: 'npm test',
    status: 'running',
    output: `> my-project@1.0.0 test
> jest

PASS src/__tests__/health.test.ts
  ✓ Health endpoint returns 200 (12ms)
  ✓ Health endpoint returns status ok (3ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.847s

Running additional test suites...`,
    exitCode: null,
    startedAt: new Date(Date.now() - 30000).toISOString(),
    completedAt: null,
    duration: null,
    filesCreated: ['src/__tests__/health.test.ts'],
    filesModified: [],
  },
]

// ─── Syntax Highlighting Helpers ────────────────────────────────────

function getFileIcon(name: string) {
  const ext = name.split('.').pop()?.toLowerCase() || ''
  if (['ts', 'tsx', 'js', 'jsx'].includes(ext)) return { icon: FileCode, color: 'text-blue-400' }
  if (['json', 'yaml', 'yml'].includes(ext)) return { icon: FileCode, color: 'text-amber-400' }
  if (['md', 'txt'].includes(ext)) return { icon: FileText, color: 'text-emerald-400' }
  if (['png', 'jpg', 'svg', 'gif'].includes(ext)) return { icon: Image, color: 'text-pink-400' }
  if (name === 'Dockerfile' || ext === 'sh') return { icon: Terminal, color: 'text-cyan-400' }
  if (ext === 'env' || name.startsWith('.env')) return { icon: File, color: 'text-yellow-400' }
  return { icon: File, color: 'text-[#9ca3af]' }
}

function getLanguageLabel(name: string): string {
  const ext = name.split('.').pop()?.toLowerCase() || ''
  if (ext === 'ts' || ext === 'tsx') return 'TypeScript'
  if (ext === 'js' || ext === 'jsx') return 'JavaScript'
  if (ext === 'json') return 'JSON'
  if (ext === 'yaml' || ext === 'yml') return 'YAML'
  if (ext === 'md') return 'Markdown'
  if (name === 'Dockerfile') return 'Dockerfile'
  if (ext === 'sh') return 'Shell'
  return 'Text'
}

function formatSize(bytes: number) {
  if (bytes === 0) return '—'
  if (bytes < 1024) return `${bytes}B`
  if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)}KB`
  return `${(bytes / 1048576).toFixed(1)}MB`
}

function timeAgo(dateStr: string) {
  const diff = Date.now() - new Date(dateStr).getTime()
  if (diff < 60000) return 'just now'
  if (diff < 3600000) return `${Math.floor(diff / 60000)}m ago`
  if (diff < 86400000) return `${Math.floor(diff / 3600000)}h ago`
  return `${Math.floor(diff / 86400000)}d ago`
}

// ─── File Tree Node Component ──────────────────────────────────────

function FileTreeNode({
  file,
  depth,
  selectedPath,
  onSelect,
  expandedPaths,
  toggleExpand,
}: {
  file: SandboxFile
  depth: number
  selectedPath: string | null
  onSelect: (file: SandboxFile) => void
  expandedPaths: Set<string>
  toggleExpand: (path: string) => void
}) {
  const isDir = file.type === 'directory'
  const isExpanded = expandedPaths.has(file.path)
  const isSelected = selectedPath === file.path
  const { icon: FileIcon, color } = isDir ? { icon: Folder, color: 'text-emerald-400' } : getFileIcon(file.name)

  return (
    <>
      <button
        onClick={() => {
          if (isDir) toggleExpand(file.path)
          onSelect(file)
        }}
        className={`w-full flex items-center gap-1.5 py-1.5 px-2 text-left text-sm transition-colors rounded-md ${
          isSelected ? 'bg-emerald-500/10 text-emerald-400' : 'text-[#d1d5db] hover:bg-[#252636]'
        }`}
        style={{ paddingLeft: `${depth * 16 + 8}px` }}
      >
        {isDir ? (
          isExpanded ? (
            <ChevronDown className="w-3 h-3 text-[#6b7280] flex-shrink-0" />
          ) : (
            <ChevronRight className="w-3 h-3 text-[#6b7280] flex-shrink-0" />
          )
        ) : (
          <span className="w-3 flex-shrink-0" />
        )}
        <FileIcon className={`w-4 h-4 flex-shrink-0 ${isDir ? (isExpanded ? 'text-emerald-400' : 'text-emerald-500/60') : color}`} />
        <span className="truncate text-xs">{file.name}</span>
        {!isDir && (
          <span className="ml-auto text-[10px] text-[#4b5563] font-mono flex-shrink-0">
            {formatSize(file.size)}
          </span>
        )}
      </button>
      {isDir && isExpanded && file.children && (
        <div>
          {file.children.map((child) => (
            <FileTreeNode
              key={child.path}
              file={child}
              depth={depth + 1}
              selectedPath={selectedPath}
              onSelect={onSelect}
              expandedPaths={expandedPaths}
              toggleExpand={toggleExpand}
            />
          ))}
        </div>
      )}
    </>
  )
}

// ─── Main Sandbox Component ────────────────────────────────────────

export function AgentSandbox() {
  const { addToast } = useAgentOSStore()

  // State
  const [fileTree, setFileTree] = useState<SandboxFile[]>(DEMO_FILE_TREE)
  const [processes, setProcesses] = useState<SandboxProcess[]>(DEMO_PROCESSES)
  const [selectedFilePath, setSelectedFilePath] = useState<string | null>('/sandbox/my-project/src/index.ts')
  const [expandedPaths, setExpandedPaths] = useState<Set<string>>(
    new Set(['/sandbox/my-project', '/sandbox/my-project/src', '/sandbox/my-project/src/utils'])
  )
  const [activeTab, setActiveTab] = useState<'files' | 'processes' | 'output'>('files')
  const [selectedProcessId, setSelectedProcessId] = useState<string | null>('proc-5')
  const [searchQuery, setSearchQuery] = useState('')
  const [sandboxDir, setSandboxDir] = useState('/sandbox')
  const [isRunning, setIsRunning] = useState(false)
  const [liveOutput, setLiveOutput] = useState('')
  const liveOutputRef = useRef<HTMLDivElement>(null)

  // Find selected file content
  const findFile = useCallback((files: SandboxFile[], path: string): SandboxFile | null => {
    for (const f of files) {
      if (f.path === path) return f
      if (f.children) {
        const found = findFile(f.children, path)
        if (found) return found
      }
    }
    return null
  }, [])

  const selectedFile = useMemo(
    () => (selectedFilePath ? findFile(fileTree, selectedFilePath) : null),
    [selectedFilePath, fileTree, findFile]
  )

  const selectedProcess = useMemo(
    () => processes.find((p) => p.id === selectedProcessId) || null,
    [processes, selectedProcessId]
  )

  // Stats
  const runningCount = processes.filter((p) => p.status === 'running').length
  const completedCount = processes.filter((p) => p.status === 'completed').length
  const failedCount = processes.filter((p) => p.status === 'failed').length

  const allFiles = useMemo(() => {
    const result: SandboxFile[] = []
    const walk = (files: SandboxFile[]) => {
      for (const f of files) {
        if (f.type === 'file') result.push(f)
        if (f.children) walk(f.children)
      }
    }
    walk(fileTree)
    return result
  }, [fileTree])

  const totalSize = allFiles.reduce((sum, f) => sum + f.size, 0)

  // Handlers
  const toggleExpand = (path: string) => {
    setExpandedPaths((prev) => {
      const next = new Set(prev)
      if (next.has(path)) next.delete(path)
      else next.add(path)
      return next
    })
  }

  const handleRunAgent = async () => {
    if (isRunning) return
    setIsRunning(true)
    setLiveOutput('')
    setActiveTab('output')

    const newProcess: SandboxProcess = {
      id: `proc-${Date.now()}`,
      agentId: 'agent-live',
      agentName: 'Full Stack Engineer',
      agentAvatar: '🦾',
      command: 'npx tsc && npm run build',
      status: 'running',
      output: '',
      exitCode: null,
      startedAt: new Date().toISOString(),
      completedAt: null,
      duration: null,
      filesCreated: [],
      filesModified: [],
    }

    setProcesses((prev) => [...prev, newProcess])
    setSelectedProcessId(newProcess.id)

    // Simulate live output
    const lines = [
      { delay: 500, text: '$ npx tsc --noEmit' },
      { delay: 1500, text: 'Checking TypeScript types...' },
      { delay: 2500, text: '  src/index.ts ............ OK' },
      { delay: 3000, text: '  src/config.ts ........... OK' },
      { delay: 3500, text: '  src/routes.ts ........... OK' },
      { delay: 4000, text: '  src/utils/logger.ts ..... OK' },
      { delay: 5000, text: 'No errors found. Type checking passed.\n' },
      { delay: 5500, text: '$ npm run build' },
      { delay: 6500, text: '> my-project@1.0.0 build' },
      { delay: 7000, text: '> tsc\n' },
      { delay: 8500, text: 'Compilation complete. Output written to ./dist/' },
      { delay: 9000, text: '  dist/index.js ........... created (2.1KB)' },
      { delay: 9500, text: '  dist/config.js .......... created (0.8KB)' },
      { delay: 10000, text: '  dist/routes.js .......... created (1.5KB)' },
      { delay: 10500, text: '  dist/utils/logger.js .... created (0.6KB)\n' },
      { delay: 11500, text: '✓ Build completed successfully in 5.2s' },
    ]

    let output = ''
    for (const line of lines) {
      await new Promise((r) => setTimeout(r, line.delay))
      output += (output ? '\n' : '') + line.text
      setLiveOutput(output)
      if (liveOutputRef.current) {
        liveOutputRef.current.scrollTop = liveOutputRef.current.scrollHeight
      }
    }

    setProcesses((prev) =>
      prev.map((p) =>
        p.id === newProcess.id
          ? {
              ...p,
              status: 'completed',
              output,
              exitCode: 0,
              completedAt: new Date().toISOString(),
              duration: 11500,
              filesCreated: ['dist/index.js', 'dist/config.js', 'dist/routes.js', 'dist/utils/logger.js'],
            }
          : p
      )
    )
    setIsRunning(false)
    addToast('Agent task completed successfully', 'success')
  }

  const handleStopProcess = () => {
    if (!selectedProcessId) return
    setProcesses((prev) =>
      prev.map((p) =>
        p.id === selectedProcessId
          ? { ...p, status: 'failed', exitCode: 137, completedAt: new Date().toISOString(), duration: 5000 }
          : p
      )
    )
    setIsRunning(false)
    setLiveOutput('')
    addToast('Process stopped', 'info')
  }

  const handleRefreshFiles = () => {
    addToast('File tree refreshed', 'info')
  }

  const handleCopyContent = () => {
    if (selectedFile?.content) {
      navigator.clipboard.writeText(selectedFile.content)
      addToast('File content copied to clipboard', 'success')
    }
  }

  // Filter processes by search
  const filteredProcesses = useMemo(() => {
    if (!searchQuery.trim()) return processes
    const q = searchQuery.toLowerCase()
    return processes.filter(
      (p) =>
        p.agentName.toLowerCase().includes(q) ||
        p.command.toLowerCase().includes(q) ||
        p.output.toLowerCase().includes(q)
    )
  }, [processes, searchQuery])

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <motion.h2
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="text-lg sm:text-2xl font-bold text-white flex items-center gap-2"
          >
            <Box className="w-5 h-5 sm:w-6 sm:h-6 text-emerald-400" />
            Agent Sandbox
          </motion.h2>
          <p className="text-xs sm:text-sm text-[#9ca3af] mt-1">
            Watch agents work in real-time, view files being created, and monitor execution
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleRunAgent}
            disabled={isRunning}
            className="flex items-center gap-2 px-3 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-sm rounded-lg transition-colors disabled:opacity-50"
          >
            {isRunning ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Running...
              </>
            ) : (
              <>
                <Play className="w-4 h-4" />
                Run Agent Task
              </>
            )}
          </button>
          <button
            onClick={handleRefreshFiles}
            className="p-2 bg-[#1e1f2b] text-[#9ca3af] hover:text-white rounded-lg border border-[#2d2e3d] transition-colors"
          >
            <RefreshCcw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Stats Bar */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
        <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-[#1e1f2b] border border-[#2d2e3d]">
          <Cpu className="w-4 h-4 text-emerald-400" />
          <div>
            <p className="text-sm font-bold text-white">{runningCount}</p>
            <p className="text-[10px] text-[#6b7280]">Running</p>
          </div>
        </div>
        <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-[#1e1f2b] border border-[#2d2e3d]">
          <CheckCircle className="w-4 h-4 text-emerald-400" />
          <div>
            <p className="text-sm font-bold text-white">{completedCount}</p>
            <p className="text-[10px] text-[#6b7280]">Completed</p>
          </div>
        </div>
        <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-[#1e1f2b] border border-[#2d2e3d]">
          <XCircle className="w-4 h-4 text-red-400" />
          <div>
            <p className="text-sm font-bold text-white">{failedCount}</p>
            <p className="text-[10px] text-[#6b7280]">Failed</p>
          </div>
        </div>
        <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-[#1e1f2b] border border-[#2d2e3d]">
          <FolderTree className="w-4 h-4 text-amber-400" />
          <div>
            <p className="text-sm font-bold text-white">{allFiles.length}</p>
            <p className="text-[10px] text-[#6b7280]">Files</p>
          </div>
        </div>
        <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-[#1e1f2b] border border-[#2d2e3d]">
          <HardDrive className="w-4 h-4 text-violet-400" />
          <div>
            <p className="text-sm font-bold text-white">{formatSize(totalSize)}</p>
            <p className="text-[10px] text-[#6b7280]">Total Size</p>
          </div>
        </div>
      </div>

      {/* Main Layout: 3 panels */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-3" style={{ minHeight: '600px' }}>
        {/* Left Panel: File Tree */}
        <div className="lg:col-span-3 bg-[#1e1f2b] border border-[#2d2e3d] rounded-xl overflow-hidden flex flex-col">
          <div className="flex items-center justify-between px-3 py-2 border-b border-[#2d2e3d] flex-shrink-0">
            <div className="flex items-center gap-2">
              <FolderTree className="w-4 h-4 text-emerald-400" />
              <span className="text-sm font-medium text-white">Files</span>
              <span className="text-[10px] text-[#6b7280] font-mono">{sandboxDir}</span>
            </div>
            <button
              onClick={handleRefreshFiles}
              className="p-1 text-[#6b7280] hover:text-white transition-colors"
            >
              <RefreshCcw className="w-3 h-3" />
            </button>
          </div>
          <div className="flex-1 overflow-y-auto custom-scrollbar p-1">
            {fileTree.map((file) => (
              <FileTreeNode
                key={file.path}
                file={file}
                depth={0}
                selectedPath={selectedFilePath}
                onSelect={(f) => {
                  if (f.type === 'file') {
                    setSelectedFilePath(f.path)
                  }
                }}
                expandedPaths={expandedPaths}
                toggleExpand={toggleExpand}
              />
            ))}
          </div>
        </div>

        {/* Middle Panel: File Viewer / Code Editor */}
        <div className="lg:col-span-5 bg-[#1e1f2b] border border-[#2d2e3d] rounded-xl overflow-hidden flex flex-col">
          {selectedFile ? (
            <>
              {/* File Header */}
              <div className="flex items-center justify-between px-3 py-2 border-b border-[#2d2e3d] flex-shrink-0">
                <div className="flex items-center gap-2 min-w-0">
                  {(() => {
                    const { icon: FIcon, color: fColor } = getFileIcon(selectedFile.name)
                    return <FIcon className={`w-4 h-4 flex-shrink-0 ${fColor}`} />
                  })()}
                  <span className="text-sm font-medium text-white truncate">{selectedFile.name}</span>
                  <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-[#252636] text-[#6b7280] font-mono flex-shrink-0">
                    {getLanguageLabel(selectedFile.name)}
                  </span>
                </div>
                <div className="flex items-center gap-1 flex-shrink-0">
                  <button onClick={handleCopyContent} className="p-1.5 text-[#6b7280] hover:text-white transition-colors">
                    <Copy className="w-3.5 h-3.5" />
                  </button>
                  <button onClick={() => addToast('File saved', 'success')} className="p-1.5 text-[#6b7280] hover:text-emerald-400 transition-colors">
                    <Save className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
              {/* File Path Breadcrumb */}
              <div className="flex items-center gap-1 px-3 py-1.5 border-b border-[#2d2e3d] bg-[#16171f] flex-shrink-0 overflow-x-auto">
                {selectedFile.path.split('/').filter(Boolean).map((part, i, arr) => (
                  <div key={i} className="flex items-center gap-1 flex-shrink-0">
                    {i > 0 && <ChevronRight className="w-3 h-3 text-[#4b5563]" />}
                    <span className={`text-[11px] font-mono ${i === arr.length - 1 ? 'text-white' : 'text-[#6b7280]'}`}>
                      {part}
                    </span>
                  </div>
                ))}
                <span className="ml-auto text-[10px] text-[#4b5563] font-mono flex-shrink-0">
                  {formatSize(selectedFile.size)} · {timeAgo(selectedFile.modified)}
                </span>
              </div>
              {/* Code Content */}
              <div className="flex-1 overflow-auto custom-scrollbar">
                <div className="flex">
                  {/* Line Numbers */}
                  <div className="flex-shrink-0 py-3 px-2 text-right select-none border-r border-[#2d2e3d] bg-[#16171f]">
                    {selectedFile.content?.split('\n').map((_, i) => (
                      <div key={i} className="text-[11px] font-mono text-[#4b5563] leading-5">
                        {i + 1}
                      </div>
                    ))}
                  </div>
                  {/* Code */}
                  <pre className="flex-1 p-3 text-[12px] font-mono text-[#d1d5db] leading-5 whitespace-pre-wrap">
                    {selectedFile.content || '// Empty file'}
                  </pre>
                </div>
              </div>
            </>
          ) : (
            <div className="flex-1 flex items-center justify-center text-[#6b7280]">
              <div className="text-center">
                <Code className="w-12 h-12 mx-auto mb-3 opacity-30" />
                <p className="text-sm">Select a file to view its contents</p>
                <p className="text-xs mt-1">Click any file in the tree on the left</p>
              </div>
            </div>
          )}
        </div>

        {/* Right Panel: Processes & Output */}
        <div className="lg:col-span-4 bg-[#1e1f2b] border border-[#2d2e3d] rounded-xl overflow-hidden flex flex-col">
          {/* Tabs */}
          <div className="flex border-b border-[#2d2e3d] flex-shrink-0">
            <button
              onClick={() => setActiveTab('processes')}
              className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-2.5 text-xs font-medium transition-colors ${
                activeTab === 'processes'
                  ? 'text-emerald-400 border-b-2 border-emerald-400'
                  : 'text-[#6b7280] hover:text-white'
              }`}
            >
              <Zap className="w-3.5 h-3.5" />
              Processes ({processes.length})
            </button>
            <button
              onClick={() => setActiveTab('output')}
              className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-2.5 text-xs font-medium transition-colors ${
                activeTab === 'output'
                  ? 'text-emerald-400 border-b-2 border-emerald-400'
                  : 'text-[#6b7280] hover:text-white'
              }`}
            >
              <Terminal className="w-3.5 h-3.5" />
              Output
              {runningCount > 0 && (
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
              )}
            </button>
          </div>

          {/* Search */}
          <div className="px-3 py-2 border-b border-[#2d2e3d] flex-shrink-0">
            <div className="relative">
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-[#6b7280]" />
              <input
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Filter processes..."
                className="w-full pl-8 pr-3 py-1.5 bg-[#0f1117] border border-[#2d2e3d] rounded-md text-xs text-white outline-none focus:border-emerald-500/50 placeholder:text-[#4b5563]"
              />
            </div>
          </div>

          <div className="flex-1 overflow-y-auto custom-scrollbar">
            {activeTab === 'processes' ? (
              <div className="divide-y divide-[#2d2e3d]">
                {filteredProcesses.map((proc) => {
                  const isActive = selectedProcessId === proc.id
                  const statusColors: Record<string, string> = {
                    running: 'text-emerald-400',
                    completed: 'text-emerald-400',
                    failed: 'text-red-400',
                    queued: 'text-amber-400',
                  }
                  const StatusIcon: Record<string, React.ElementType> = {
                    running: Loader2,
                    completed: CheckCircle,
                    failed: XCircle,
                    queued: Clock,
                  }
                  const SIcon = StatusIcon[proc.status] || Clock
                  return (
                    <button
                      key={proc.id}
                      onClick={() => setSelectedProcessId(proc.id)}
                      className={`w-full text-left p-3 transition-colors ${
                        isActive ? 'bg-emerald-500/10' : 'hover:bg-[#252636]'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-1">
                        <div className="flex items-center gap-2 min-w-0">
                          <span className="text-sm">{proc.agentAvatar}</span>
                          <span className="text-xs font-medium text-white truncate">{proc.agentName}</span>
                        </div>
                        <SIcon className={`w-3.5 h-3.5 flex-shrink-0 ${statusColors[proc.status]} ${proc.status === 'running' ? 'animate-spin' : ''}`} />
                      </div>
                      <div className="flex items-center gap-1.5 mb-1">
                        <span className="text-[10px] font-mono text-[#6b7280] truncate">$ {proc.command}</span>
                      </div>
                      <div className="flex items-center gap-3 text-[10px] text-[#4b5563]">
                        <span className="flex items-center gap-1">
                          <ClockIcon className="w-2.5 h-2.5" />
                          {proc.duration ? `${(proc.duration / 1000).toFixed(1)}s` : 'running...'}
                        </span>
                        {proc.exitCode !== null && (
                          <span className={proc.exitCode === 0 ? 'text-emerald-400' : 'text-red-400'}>
                            exit {proc.exitCode}
                          </span>
                        )}
                        {proc.filesCreated.length > 0 && (
                          <span className="text-amber-400">+{proc.filesCreated.length} files</span>
                        )}
                      </div>
                    </button>
                  )
                })}
                {filteredProcesses.length === 0 && (
                  <div className="text-center py-8 text-[#6b7280]">
                    <p className="text-xs">No processes found</p>
                  </div>
                )}
              </div>
            ) : (
              /* Output Tab */
              <div className="p-0">
                {/* Output Controls */}
                {selectedProcess && (
                  <div className="flex items-center justify-between px-3 py-2 border-b border-[#2d2e3d] bg-[#16171f]">
                    <div className="flex items-center gap-2 min-w-0">
                      <span className="text-sm">{selectedProcess.agentAvatar}</span>
                      <span className="text-xs font-medium text-white truncate">{selectedProcess.agentName}</span>
                      <span className="text-[10px] font-mono text-[#6b7280] truncate">$ {selectedProcess.command}</span>
                    </div>
                    <div className="flex items-center gap-1 flex-shrink-0">
                      {selectedProcess.status === 'running' && (
                        <button
                          onClick={handleStopProcess}
                          className="p-1 text-[#6b7280] hover:text-red-400 transition-colors"
                          title="Stop process"
                        >
                          <Square className="w-3.5 h-3.5" />
                        </button>
                      )}
                      <button
                        onClick={() => {
                          const text = isRunning ? liveOutput : selectedProcess.output
                          if (text) {
                            navigator.clipboard.writeText(text)
                            addToast('Output copied', 'success')
                          }
                        }}
                        className="p-1 text-[#6b7280] hover:text-white transition-colors"
                        title="Copy output"
                      >
                        <Copy className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                )}

                {/* Live or Stored Output */}
                <div
                  ref={liveOutputRef}
                  className="bg-[#0a0b0e] p-3 min-h-[300px] max-h-[500px] overflow-y-auto custom-scrollbar"
                >
                  {isRunning && liveOutput ? (
                    <pre className="text-xs font-mono text-[#d1d5db] whitespace-pre-wrap leading-5">
                      {liveOutput}
                      <span className="animate-pulse text-emerald-400">_</span>
                    </pre>
                  ) : selectedProcess?.output ? (
                    <pre className="text-xs font-mono text-[#d1d5db] whitespace-pre-wrap leading-5">
                      {selectedProcess.output}
                    </pre>
                  ) : (
                    <div className="flex items-center justify-center h-[250px] text-[#4b5563]">
                      <div className="text-center">
                        <Terminal className="w-8 h-8 mx-auto mb-2 opacity-30" />
                        <p className="text-xs">Select a process to view output</p>
                        <p className="text-[10px] mt-1">Or click "Run Agent Task" to start a new execution</p>
                      </div>
                    </div>
                  )}
                </div>

                {/* Files Created by Selected Process */}
                {selectedProcess && (selectedProcess.filesCreated.length > 0 || selectedProcess.filesModified.length > 0) && (
                  <div className="px-3 py-2 border-t border-[#2d2e3d]">
                    <p className="text-[10px] font-medium text-[#6b7280] uppercase tracking-wider mb-1.5">File Changes</p>
                    <div className="space-y-1">
                      {selectedProcess.filesCreated.map((f) => (
                        <div key={f} className="flex items-center gap-2 text-[11px]">
                          <span className="text-emerald-400 font-mono">+</span>
                          <span className="text-[#d1d5db] font-mono truncate">{f}</span>
                        </div>
                      ))}
                      {selectedProcess.filesModified.map((f) => (
                        <div key={f} className="flex items-center gap-2 text-[11px]">
                          <span className="text-amber-400 font-mono">~</span>
                          <span className="text-[#d1d5db] font-mono truncate">{f}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Quick Actions */}
      <div className="space-y-2">
        <h3 className="text-sm font-medium text-[#9ca3af]">Sandbox Quick Actions</h3>
        <div className="flex flex-wrap gap-2">
          {[
            { label: 'New Sandbox', icon: Plus, action: () => addToast('New sandbox created', 'success') },
            { label: 'Run Tests', icon: Play, action: handleRunAgent },
            { label: 'Clean Build', icon: RotateCcw, action: () => addToast('Clean build started', 'info') },
            { label: 'Download All', icon: Download, action: () => addToast('Downloading sandbox files...', 'info') },
            { label: 'Reset Sandbox', icon: Trash2, action: () => addToast('Sandbox reset to clean state', 'info') },
          ].map((qa) => (
            <button
              key={qa.label}
              onClick={qa.action}
              className="flex items-center gap-2 px-3 py-2 text-xs bg-[#1e1f2b] text-[#9ca3af] hover:text-white hover:bg-[#252636] rounded-lg border border-[#2d2e3d] transition-colors"
            >
              <qa.icon className="w-3.5 h-3.5" />
              {qa.label}
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}
