'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Puzzle,
  Plus,
  Trash2,
  Power,
  PowerOff,
  Star,
  Download,
  Settings,
  Search,
  ChevronDown,
  ExternalLink,
  CheckCircle,
  XCircle,
  Tag,
  Code,
  Zap,
  Globe,
  Palette,
  Bot,
  Wrench,
} from 'lucide-react'
import { useAgentOSStore } from '@/lib/store'

interface Plugin {
  id: string
  name: string
  description: string
  version: string
  author: string
  category: string
  icon: string
  entryPoint: string
  config: string
  permissions: string[]
  hooks: string[]
  isActive: boolean
  isInstalled: boolean
  isBuiltIn: boolean
  rating: number
  installCount: number
  createdAt: string
}

const builtInPlugins: Omit<Plugin, 'id' | 'createdAt'>[] = [
  {
    name: 'Auto-Memory',
    description: 'Automatically captures and stores important conversation insights into the memory vault. Uses smart extraction to identify key information worth preserving.',
    version: '2.1.0',
    author: 'AgentOS Team',
    category: 'utility',
    icon: '🧠',
    entryPoint: '/plugins/auto-memory',
    config: '{}',
    permissions: ['memory:write', 'memory:read'],
    hooks: ['chat:after', 'agent:output'],
    isActive: true,
    isInstalled: true,
    isBuiltIn: true,
    rating: 4.8,
    installCount: 2847,
  },
  {
    name: 'Slack Bridge',
    description: 'Two-way integration with Slack workspaces. Send agent notifications to channels and trigger agents from Slack commands. Supports slash commands and thread replies.',
    version: '1.4.2',
    author: 'Community',
    category: 'integration',
    icon: '💬',
    entryPoint: '/plugins/slack-bridge',
    config: '{}',
    permissions: ['webhook:send', 'webhook:receive', 'notification:write'],
    hooks: ['notification:new', 'webhook:incoming'],
    isActive: false,
    isInstalled: true,
    isBuiltIn: true,
    rating: 4.5,
    installCount: 1523,
  },
  {
    name: 'Code Guardian',
    description: 'Automatically reviews code generated by agents for security vulnerabilities, best practices, and performance issues. Integrates with the loop system for output validation.',
    version: '1.2.0',
    author: 'AgentOS Team',
    category: 'agent',
    icon: '🛡️',
    entryPoint: '/plugins/code-guardian',
    config: '{}',
    permissions: ['agent:read', 'output:read', 'output:write'],
    hooks: ['agent:output', 'workflow:step:after'],
    isActive: false,
    isInstalled: true,
    isBuiltIn: true,
    rating: 4.6,
    installCount: 1891,
  },
  {
    name: 'Neon Dreams',
    description: 'A cyberpunk-inspired theme with neon gradients, glitch effects, and holographic UI elements. Transforms the entire AgentOS interface into a retro-futuristic experience.',
    version: '3.0.1',
    author: 'Design Lab',
    category: 'theme',
    icon: '🎨',
    entryPoint: '/plugins/neon-dreams',
    config: '{}',
    permissions: ['ui:theme'],
    hooks: ['ui:render'],
    isActive: false,
    isInstalled: true,
    isBuiltIn: true,
    rating: 4.9,
    installCount: 3210,
  },
  {
    name: 'Python Runner',
    description: 'Execute Python scripts from within AgentOS. Provides a sandboxed environment with pre-installed data science libraries. Supports output capture and error reporting.',
    version: '1.1.0',
    author: 'Community',
    category: 'language',
    icon: '🐍',
    entryPoint: '/plugins/python-runner',
    config: '{}',
    permissions: ['terminal:execute', 'file:read', 'file:write'],
    hooks: ['command:execute', 'workflow:step'],
    isActive: false,
    isInstalled: true,
    isBuiltIn: true,
    rating: 4.3,
    installCount: 987,
  },
  {
    name: 'Smart Scheduler',
    description: 'Enhanced scheduling with natural language input. Instead of cron expressions, describe when you want tasks to run. Also adds retry logic and failure escalation policies.',
    version: '2.0.0',
    author: 'AgentOS Team',
    category: 'utility',
    icon: '⏰',
    entryPoint: '/plugins/smart-scheduler',
    config: '{}',
    permissions: ['scheduler:read', 'scheduler:write', 'notification:write'],
    hooks: ['scheduler:before', 'scheduler:after', 'scheduler:error'],
    isActive: true,
    isInstalled: true,
    isBuiltIn: true,
    rating: 4.7,
    installCount: 2156,
  },
  {
    name: 'GitHub Sync',
    description: 'Sync agent outputs directly to GitHub repositories. Create commits, PRs, and issues from agent outputs. Also monitors repo webhooks for triggering workflows.',
    version: '1.3.0',
    author: 'Community',
    category: 'integration',
    icon: '🐙',
    entryPoint: '/plugins/github-sync',
    config: '{}',
    permissions: ['webhook:send', 'webhook:receive', 'output:read'],
    hooks: ['output:new', 'webhook:incoming'],
    isActive: false,
    isInstalled: true,
    isBuiltIn: true,
    rating: 4.4,
    installCount: 1340,
  },
  {
    name: 'Markdown Wizard',
    description: 'Convert any agent output to beautifully formatted Markdown with syntax highlighting, tables, and embedded charts. Perfect for documentation generation workflows.',
    version: '1.0.2',
    author: 'AgentOS Team',
    category: 'utility',
    icon: '📝',
    entryPoint: '/plugins/markdown-wizard',
    config: '{}',
    permissions: ['output:read', 'output:write'],
    hooks: ['output:new', 'loop:before'],
    isActive: false,
    isInstalled: true,
    isBuiltIn: true,
    rating: 4.2,
    installCount: 765,
  },
]

export function PluginSystem() {
  const { addToast } = useAgentOSStore()
  const [plugins, setPlugins] = useState<Plugin[]>([])
  const [searchQuery, setSearchQuery] = useState('')
  const [activeCategory, setActiveCategory] = useState('all')
  const [expandedPlugin, setExpandedPlugin] = useState<string | null>(null)

  useEffect(() => {
    fetchPlugins()
  }, [])

  const fetchPlugins = async () => {
    try {
      const res = await fetch('/api/plugins')
      if (res.ok) {
        const data = await res.json()
        if (data.length > 0) {
          setPlugins(data)
        } else {
          // Seed with built-in plugins
          setPlugins(builtInPlugins.map((p, i) => ({
            ...p,
            id: `builtin-${i + 1}`,
            createdAt: new Date().toISOString(),
          })) as Plugin[])
        }
      }
    } catch {
      setPlugins(builtInPlugins.map((p, i) => ({
        ...p,
        id: `builtin-${i + 1}`,
        createdAt: new Date().toISOString(),
      })) as Plugin[])
    }
  }

  const togglePlugin = async (id: string, isActive: boolean) => {
    try {
      const res = await fetch(`/api/plugins/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isActive: !isActive }),
      })
      if (res.ok) {
        setPlugins((prev) =>
          prev.map((p) => (p.id === id ? { ...p, isActive: !isActive } : p))
        )
        addToast(`Plugin ${!isActive ? 'enabled' : 'disabled'}`, 'success')
      }
    } catch {
      addToast('Failed to toggle plugin', 'error')
    }
  }

  const filteredPlugins = plugins.filter((p) => {
    const matchesSearch =
      !searchQuery ||
      p.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.description.toLowerCase().includes(searchQuery.toLowerCase())
    const matchesCategory = activeCategory === 'all' || p.category === activeCategory
    return matchesSearch && matchesCategory
  })

  const categories = [
    { id: 'all', label: 'All', icon: Puzzle },
    { id: 'utility', label: 'Utility', icon: Wrench },
    { id: 'integration', label: 'Integration', icon: Globe },
    { id: 'agent', label: 'Agent', icon: Bot },
    { id: 'theme', label: 'Theme', icon: Palette },
    { id: 'language', label: 'Language', icon: Code },
  ]

  const activePlugins = plugins.filter((p) => p.isActive).length

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold text-white flex items-center gap-2">
            <Puzzle className="w-5 h-5 text-emerald-400" />
            Plugin System
          </h2>
          <p className="text-sm text-[#9ca3af] mt-1">Extend AgentOS with community and custom plugins</p>
        </div>
        <div className="flex items-center gap-2">
          <div className="px-2 py-1 bg-emerald-500/10 text-emerald-400 rounded-lg text-xs font-medium">
            {activePlugins} active
          </div>
          <div className="px-2 py-1 bg-[#1e1f2b] text-[#9ca3af] rounded-lg text-xs border border-[#2d2e3d]">
            {plugins.length} total
          </div>
        </div>
      </div>

      {/* Search + Categories */}
      <div className="space-y-3">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#6b7280]" />
          <input
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-3 py-2 bg-[#1e1f2b] border border-[#2d2e3d] rounded-lg text-white text-sm outline-none focus:border-emerald-500"
            placeholder="Search plugins..."
          />
        </div>
        <div className="flex gap-1 overflow-x-auto custom-scrollbar pb-1">
          {categories.map((cat) => (
            <button
              key={cat.id}
              onClick={() => setActiveCategory(cat.id)}
              className={`flex items-center gap-1.5 px-3 py-1.5 text-xs rounded-lg transition-colors flex-shrink-0 ${
                activeCategory === cat.id
                  ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
                  : 'bg-[#1e1f2b] text-[#9ca3af] border border-[#2d2e3d] hover:text-white'
              }`}
            >
              <cat.icon className="w-3 h-3" />
              {cat.label}
            </button>
          ))}
        </div>
      </div>

      {/* Plugin Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {filteredPlugins.map((plugin) => (
          <motion.div
            key={plugin.id}
            layout
            className="bg-[#1e1f2b] border border-[#2d2e3d] rounded-lg overflow-hidden"
          >
            <div className="p-4">
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-3">
                  <div className="w-10 h-10 rounded-lg bg-[#0f1117] flex items-center justify-center text-lg flex-shrink-0">
                    {plugin.icon}
                  </div>
                  <div className="min-w-0">
                    <div className="flex items-center gap-2">
                      <h4 className="text-sm font-semibold text-white">{plugin.name}</h4>
                      {plugin.isBuiltIn && (
                        <span className="px-1.5 py-0.5 text-[9px] bg-violet-500/10 text-violet-400 rounded font-medium">
                          BUILT-IN
                        </span>
                      )}
                    </div>
                    <p className="text-xs text-[#9ca3af] mt-0.5 line-clamp-2">{plugin.description}</p>
                  </div>
                </div>
                <button
                  onClick={() => togglePlugin(plugin.id, plugin.isActive)}
                  className={`flex-shrink-0 p-1.5 rounded-lg transition-colors ${
                    plugin.isActive
                      ? 'bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20'
                      : 'bg-[#252636] text-[#6b7280] hover:text-white'
                  }`}
                  title={plugin.isActive ? 'Disable' : 'Enable'}
                >
                  {plugin.isActive ? <Power className="w-4 h-4" /> : <PowerOff className="w-4 h-4" />}
                </button>
              </div>

              <div className="flex items-center gap-3 mt-3 text-[10px] text-[#6b7280]">
                <span className="flex items-center gap-1">
                  <Tag className="w-2.5 h-2.5" />
                  v{plugin.version}
                </span>
                <span>by {plugin.author}</span>
                <span className="flex items-center gap-0.5">
                  <Star className="w-2.5 h-2.5 text-amber-400 fill-amber-400" />
                  {plugin.rating}
                </span>
                <span className="flex items-center gap-0.5">
                  <Download className="w-2.5 h-2.5" />
                  {plugin.installCount.toLocaleString()}
                </span>
              </div>

              {/* Expanded Details */}
              <button
                onClick={() => setExpandedPlugin(expandedPlugin === plugin.id ? null : plugin.id)}
                className="flex items-center gap-1 mt-2 text-[10px] text-[#6b7280] hover:text-white transition-colors"
              >
                {expandedPlugin === plugin.id ? 'Less' : 'More details'}
                <ChevronDown className={`w-3 h-3 transition-transform ${expandedPlugin === plugin.id ? 'rotate-180' : ''}`} />
              </button>

              <AnimatePresence>
                {expandedPlugin === plugin.id && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="overflow-hidden"
                  >
                    <div className="mt-3 pt-3 border-t border-[#2d2e3d] space-y-2">
                      <div>
                        <span className="text-[10px] text-[#6b7280] uppercase">Permissions:</span>
                        <div className="flex flex-wrap gap-1 mt-1">
                          {plugin.permissions.map((perm) => (
                            <span key={perm} className="px-1.5 py-0.5 bg-[#0f1117] text-[9px] text-amber-400 rounded border border-[#2d2e3d] font-mono">
                              {perm}
                            </span>
                          ))}
                        </div>
                      </div>
                      <div>
                        <span className="text-[10px] text-[#6b7280] uppercase">Event Hooks:</span>
                        <div className="flex flex-wrap gap-1 mt-1">
                          {plugin.hooks.map((hook) => (
                            <span key={hook} className="px-1.5 py-0.5 bg-[#0f1117] text-[9px] text-cyan-400 rounded border border-[#2d2e3d] font-mono">
                              {hook}
                            </span>
                          ))}
                        </div>
                      </div>
                      <div>
                        <span className="text-[10px] text-[#6b7280] uppercase">Entry Point:</span>
                        <code className="ml-1 text-[9px] text-emerald-400 font-mono">{plugin.entryPoint}</code>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Marketplace CTA */}
      <div className="bg-gradient-to-r from-emerald-500/10 to-violet-500/10 border border-[#2d2e3d] rounded-lg p-6 text-center">
        <h3 className="text-sm font-semibold text-white">Plugin Marketplace</h3>
        <p className="text-xs text-[#9ca3af] mt-1 max-w-md mx-auto">
          Discover community-built plugins, rate your favorites, and submit your own creations to the marketplace.
        </p>
        <button className="mt-3 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-sm rounded-lg transition-colors">
          Browse Marketplace
        </button>
      </div>
    </div>
  )
}
